from termbase.models import Storyboard


def load_storyboard_fixture() -> Storyboard:
    return Storyboard.model_validate(
        {
            "term": "DNS",
            "summary": "DNSをネットの電話帳に例えながら、先生と生徒の会話で理解する構成。",
            "llm_prompt_log": {
                "output_rules_version": "script-json-v4",
                "system_prompt": "stub",
                "user_prompt": "stub",
            },
            "scenes": [
                {
                    "scene_id": 1,
                    "title": "名前だけでは届かない",
                    "speaker_role": "student",
                    "primary_visual_role": "student",
                    "expression": "confused",
                    "narration": "DNSの意味を説明してって言われると、サイト名は分かってもどこへつなげばいいのかまだわからないんです。",
                    "speech_bubble_text": "どこにつながるんすか？",
                    "subtitle": "DNSの意味を説明してって言われると、サイト名は分かってもどこへつなげばいいのかまだわからないんです。",
                    "duration_sec": 10,
                    "visual_summary": "困っている生徒がPC画面を見て首をかしげる。",
                    "emotion_parameters": {"style": "困惑", "intensity": 0.74},
                },
                {
                    "scene_id": 2,
                    "title": "先生が問題を整理",
                    "speaker_role": "teacher",
                    "primary_visual_role": "teacher",
                    "expression": "explaining",
                    "narration": "大丈夫。DNSは名前と行き先を結びつける話なんだ、と考えると見えやすいですよ。",
                    "speech_bubble_text": "まずは落ち着いて整理しましょ。",
                    "subtitle": "大丈夫。DNSは名前と行き先を結びつける話なんだ、と考えると見えやすいですよ。",
                    "duration_sec": 10,
                    "visual_summary": "先生が落ち着いて問題を整理して見せる。",
                    "emotion_parameters": {"style": "説明", "intensity": 0.52},
                },
                {
                    "scene_id": 3,
                    "title": "電話帳で考える",
                    "speaker_role": "teacher",
                    "primary_visual_role": "teacher",
                    "expression": "thinking",
                    "narration": "たとえば友だちの名前から電話番号を探す電話帳みたいに、DNSは名前から行き先を探します。",
                    "speech_bubble_text": "DNSはネットの電話帳です。",
                    "subtitle": "たとえば友だちの名前から電話番号を探す電話帳みたいに、DNSは名前から行き先を探します。",
                    "duration_sec": 12,
                    "visual_summary": "電話帳の比喩を使って先生が説明する。",
                    "emotion_parameters": {"style": "説明", "intensity": 0.61},
                },
                {
                    "scene_id": 4,
                    "title": "名前を住所へ変換",
                    "speaker_role": "teacher",
                    "primary_visual_role": "teacher",
                    "expression": "explaining",
                    "narration": "ブラウザはまず名前を受け取り、DNSに問い合わせて数字の住所へ変換してもらいます。",
                    "speech_bubble_text": "名前を住所に変える役目です。",
                    "subtitle": "ブラウザはまず名前を受け取り、DNSに問い合わせて数字の住所へ変換してもらいます。",
                    "duration_sec": 11,
                    "visual_summary": "名前から数字の住所へ変換される図を先生が示す。",
                    "emotion_parameters": {"style": "説明", "intensity": 0.56},
                },
                {
                    "scene_id": 5,
                    "title": "生徒が整理する",
                    "speaker_role": "student",
                    "primary_visual_role": "student",
                    "expression": "thinking",
                    "narration": "つまり、サイト名だけでは届かないから、先に数字の住所を調べる必要があるんですね。",
                    "speech_bubble_text": "先に住所確認なんですね！",
                    "subtitle": "つまり、サイト名だけでは届かないから、先に数字の住所を調べる必要があるんですね。",
                    "duration_sec": 10,
                    "visual_summary": "生徒が頭の中で流れを整理している。",
                    "emotion_parameters": {"style": "理解", "intensity": 0.58},
                },
                {
                    "scene_id": 6,
                    "title": "問い合わせ先を知る",
                    "speaker_role": "teacher",
                    "primary_visual_role": "teacher",
                    "expression": "serious",
                    "narration": "そうです。だからDNSが止まると、名前は分かっていても目的のサイトへたどり着きにくくなります。",
                    "speech_bubble_text": "DNSが止まると迷子になります。",
                    "subtitle": "そうです。だからDNSが止まると、名前は分かっていても目的のサイトへたどり着きにくくなります。",
                    "duration_sec": 12,
                    "visual_summary": "DNS停止で迷子になるイメージを先生が強調する。",
                    "emotion_parameters": {"style": "強調", "intensity": 0.67},
                },
                {
                    "scene_id": 7,
                    "title": "生徒が納得する",
                    "speaker_role": "student",
                    "primary_visual_role": "student",
                    "expression": "surprised",
                    "narration": "名前しか見えていない私たちの代わりに、裏で住所を調べてくれる仕組みだったんですね。",
                    "speech_bubble_text": "裏で探してくれてたんだ！",
                    "subtitle": "名前しか見えていない私たちの代わりに、裏で住所を調べてくれる仕組みだったんですね。",
                    "duration_sec": 10,
                    "visual_summary": "生徒が気づいた表情で理解を深める。",
                    "emotion_parameters": {"style": "気づき", "intensity": 0.64},
                },
                {
                    "scene_id": 8,
                    "title": "先生が要点を再確認",
                    "speaker_role": "teacher",
                    "primary_visual_role": "teacher",
                    "expression": "explaining",
                    "narration": "DNSは名前と数字の住所を結びつける案内役、と覚えておけばかなり理解しやすくなります。",
                    "speech_bubble_text": "案内役だと思えば大丈夫です。",
                    "subtitle": "DNSは名前と数字の住所を結びつける案内役、と覚えておけばかなり理解しやすくなります。",
                    "duration_sec": 11,
                    "visual_summary": "先生が要点を簡潔にまとめる。",
                    "emotion_parameters": {"style": "整理", "intensity": 0.55},
                },
                {
                    "scene_id": 9,
                    "title": "身近な感覚へ戻す",
                    "speaker_role": "student",
                    "primary_visual_role": "student",
                    "expression": "happy",
                    "narration": "電話帳のたとえで考えると、急に難しい言葉じゃなくなってきました。",
                    "speech_bubble_text": "たしかに電話帳っぽいです！",
                    "subtitle": "電話帳のたとえで考えると、急に難しい言葉じゃなくなってきました。",
                    "duration_sec": 9,
                    "visual_summary": "生徒が明るい表情で理解の手応えを感じる。",
                    "emotion_parameters": {"style": "安心", "intensity": 0.63},
                },
                {
                    "scene_id": 10,
                    "title": "最後の確認",
                    "speaker_role": "teacher",
                    "primary_visual_role": "teacher",
                    "expression": "smile",
                    "narration": "名前から正しい行き先を見つける。その一歩を支えるのがDNSです。",
                    "speech_bubble_text": "DNSが最初の一歩を支えます。",
                    "subtitle": "名前から正しい行き先を見つける。その一歩を支えるのがDNSです。",
                    "duration_sec": 9,
                    "visual_summary": "先生がやさしく最終確認をする。",
                    "emotion_parameters": {"style": "安心", "intensity": 0.49},
                },
                {
                    "scene_id": 11,
                    "title": "生徒の理解が完成",
                    "speaker_role": "student",
                    "primary_visual_role": "student",
                    "expression": "happy",
                    "narration": "名前だけでは届かないときに、行き先を探してくれる案内役だと分かりました。",
                    "speech_bubble_text": "なるほど、案内役ですね！",
                    "subtitle": "名前だけでは届かないときに、行き先を探してくれる案内役だと分かりました。",
                    "duration_sec": 9,
                    "visual_summary": "生徒が自信を持って理解を口にする。",
                    "emotion_parameters": {"style": "納得", "intensity": 0.66},
                },
                {
                    "scene_id": 12,
                    "title": "決め台詞で締める",
                    "speaker_role": "teacher",
                    "primary_visual_role": "teacher",
                    "expression": "smile",
                    "narration": "DNSの説明、できるようになりましたか？ もっと深掘りしたい方はチャンネル登録をして、ほかの動画もぜひ見てみてください。",
                    "speech_bubble_text": "次も一緒に整理しましょう。",
                    "subtitle": "DNSの説明、できるようになりましたか？ もっと深掘りしたい方はチャンネル登録をして、ほかの動画もぜひ見てみてください。",
                    "duration_sec": 11,
                    "visual_summary": "先生が笑顔で理解確認と視聴導線を案内して締める。",
                    "emotion_parameters": {"style": "締め", "intensity": 0.7},
                },
            ],
        }
    )
