from termbase.models import Storyboard


def load_storyboard_fixture() -> Storyboard:
    return Storyboard.model_validate(
        {
            "term": "GET / POST",
            "summary": "GETとPOSTの違いを郵便ポストの例えを使いながら、先生と生徒の会話で理解する構成。",
            "llm_prompt_log": {
                "output_rules_version": "script-json-v4",
                "system_prompt": "stub",
                "user_prompt": "stub",
            },
            "scenes": [
                {
                    "scene_id": 1,
                    "title": "リクエストの種類に迷う",
                    "speaker_role": "student",
                    "primary_visual_role": "student",
                    "expression": "confused",
                    "narration": "GET / POST って、なんで2種類もあるんですか？意味がよく分からなくて困っています。",
                    "speech_bubble_text": "なんで2種類あるんすか？",
                    "subtitle": "GET / POST って、なんで2種類もあるんですか？意味がよく分からなくて困っています。",
                    "duration_sec": 10,
                    "visual_summary": "生徒がPCを見ながら首をかしげて困っている。",
                    "emotion_parameters": {"style": "困惑", "intensity": 0.75},
                },
                {
                    "scene_id": 2,
                    "title": "先生が問題を整理",
                    "speaker_role": "teacher",
                    "primary_visual_role": "teacher",
                    "expression": "explaining",
                    "narration": "まず、HTTPリクエストには目的によって使い分ける種類があります。まずGETかPOSTかで整理すると意味が見えやすいですよ。",
                    "speech_bubble_text": "まず目的を確認しましょ。",
                    "subtitle": "まず、HTTPリクエストには目的によって使い分ける種類があります。まずGETかPOSTかで整理すると意味が見えやすいですよ。",
                    "duration_sec": 12,
                    "visual_summary": "先生が落ち着いてリクエストの種類を整理して見せる。",
                    "emotion_parameters": {"style": "説明", "intensity": 0.55},
                },
                {
                    "scene_id": 3,
                    "title": "郵便ポストで例える",
                    "speaker_role": "teacher",
                    "primary_visual_role": "teacher",
                    "expression": "thinking",
                    "narration": "たとえば郵便ポストみたいに考えてみてください。GETは手紙を取り出す動作で、POSTは手紙を投函する動作です。",
                    "speech_bubble_text": "ポストのGETとPOSTです。",
                    "subtitle": "たとえば郵便ポストみたいに考えてみてください。GETは手紙を取り出す動作で、POSTは手紙を投函する動作です。",
                    "duration_sec": 12,
                    "visual_summary": "先生が郵便ポストの比喩を使って説明する。",
                    "emotion_parameters": {"style": "説明", "intensity": 0.62},
                },
                {
                    "scene_id": 4,
                    "title": "GETはデータを取得する",
                    "speaker_role": "teacher",
                    "primary_visual_role": "teacher",
                    "expression": "explaining",
                    "narration": "GETはサーバーからデータを取ってくるためのリクエストです。ページを開くときなどに使います。",
                    "speech_bubble_text": "GETはデータを取るだけ。",
                    "subtitle": "GETはサーバーからデータを取ってくるためのリクエストです。ページを開くときなどに使います。",
                    "duration_sec": 11,
                    "visual_summary": "先生がGETリクエストの流れを示す図を説明する。",
                    "emotion_parameters": {"style": "説明", "intensity": 0.57},
                },
                {
                    "scene_id": 5,
                    "title": "POSTはデータを送る",
                    "speaker_role": "teacher",
                    "primary_visual_role": "teacher",
                    "expression": "serious",
                    "narration": "一方でPOSTはデータをサーバーに送るためのリクエストです。フォームの送信やログインなどで使います。",
                    "speech_bubble_text": "POSTはデータを送ります。",
                    "subtitle": "一方でPOSTはデータをサーバーに送るためのリクエストです。フォームの送信やログインなどで使います。",
                    "duration_sec": 11,
                    "visual_summary": "先生がPOSTリクエストの送信の流れを示す。",
                    "emotion_parameters": {"style": "説明", "intensity": 0.58},
                },
                {
                    "scene_id": 6,
                    "title": "生徒が整理する",
                    "speaker_role": "student",
                    "primary_visual_role": "student",
                    "expression": "thinking",
                    "narration": "つまりGETは取ってくる、POSTは送る、ということですね。目的が違うから2種類あるんですね。",
                    "speech_bubble_text": "取る・送るで分けるんですね！",
                    "subtitle": "つまりGETは取ってくる、POSTは送る、ということですね。目的が違うから2種類あるんですね。",
                    "duration_sec": 10,
                    "visual_summary": "生徒がGETとPOSTの違いを頭の中で整理している。",
                    "emotion_parameters": {"style": "理解", "intensity": 0.59},
                },
                {
                    "scene_id": 7,
                    "title": "URLの見え方の違い",
                    "speaker_role": "teacher",
                    "primary_visual_role": "teacher",
                    "expression": "explaining",
                    "narration": "GETではデータがURLに含まれることが多いですが、POSTではリクエスト本体にデータが入ります。",
                    "speech_bubble_text": "GETはURLに出ますよ。",
                    "subtitle": "GETではデータがURLに含まれることが多いですが、POSTではリクエスト本体にデータが入ります。",
                    "duration_sec": 11,
                    "visual_summary": "先生がGETのURLとPOSTの本体の違いを示す。",
                    "emotion_parameters": {"style": "強調", "intensity": 0.64},
                },
                {
                    "scene_id": 8,
                    "title": "生徒がセキュリティに気づく",
                    "speaker_role": "student",
                    "primary_visual_role": "student",
                    "expression": "surprised",
                    "narration": "あ、だからログインフォームはPOSTなんですね。パスワードをURLに出したくないから。",
                    "speech_bubble_text": "パスワードがURLに出るのはマズい！",
                    "subtitle": "あ、だからログインフォームはPOSTなんですね。パスワードをURLに出したくないから。",
                    "duration_sec": 10,
                    "visual_summary": "生徒が気づいた表情でセキュリティの理由を理解する。",
                    "emotion_parameters": {"style": "気づき", "intensity": 0.66},
                },
                {
                    "scene_id": 9,
                    "title": "先生が要点をまとめる",
                    "speaker_role": "teacher",
                    "primary_visual_role": "teacher",
                    "expression": "smile",
                    "narration": "そうです。GETは取得、POSTは送信、目的に合わせて使い分けるのが基本です。",
                    "speech_bubble_text": "目的で選べば大丈夫です。",
                    "subtitle": "そうです。GETは取得、POSTは送信、目的に合わせて使い分けるのが基本です。",
                    "duration_sec": 10,
                    "visual_summary": "先生がGETとPOSTの使い分けの要点を笑顔でまとめる。",
                    "emotion_parameters": {"style": "整理", "intensity": 0.53},
                },
                {
                    "scene_id": 10,
                    "title": "たとえで手応えをつかむ",
                    "speaker_role": "student",
                    "primary_visual_role": "student",
                    "expression": "happy",
                    "narration": "郵便ポストのたとえで、急にGETとPOSTが身近に感じられました。",
                    "speech_bubble_text": "ポストで覚えられます！",
                    "subtitle": "郵便ポストのたとえで、急にGETとPOSTが身近に感じられました。",
                    "duration_sec": 9,
                    "visual_summary": "生徒が明るい表情でGETとPOSTの理解の手応えを感じる。",
                    "emotion_parameters": {"style": "安心", "intensity": 0.61},
                },
                {
                    "scene_id": 11,
                    "title": "まとめで確認",
                    "speaker_role": "teacher",
                    "primary_visual_role": "teacher",
                    "expression": "explaining",
                    "narration": "GET / POST の使い分け、説明できそうですか？目的ベースで考えれば整理しやすいですよ。",
                    "speech_bubble_text": "GET / POST は目的で決まります。",
                    "subtitle": "GET / POST の使い分け、説明できそうですか？目的ベースで考えれば整理しやすいですよ。",
                    "duration_sec": 9,
                    "visual_summary": "先生が最終確認としてGETとPOSTの要点をやさしくまとめる。",
                    "emotion_parameters": {"style": "安心", "intensity": 0.51},
                },
                {
                    "scene_id": 12,
                    "title": "決め台詞で締める",
                    "speaker_role": "student",
                    "primary_visual_role": "student",
                    "expression": "happy",
                    "narration": "GET / POST の違い、もっと深掘りしたい方はチャンネル登録をして、ほかの動画もぜひ見てみてください。",
                    "speech_bubble_text": "次も一緒に整理しましょう！",
                    "subtitle": "GET / POST の違い、もっと深掘りしたい方はチャンネル登録をして、ほかの動画もぜひ見てみてください。",
                    "duration_sec": 9,
                    "visual_summary": "生徒が笑顔でチャンネル登録を案内して締める。",
                    "emotion_parameters": {"style": "締め", "intensity": 0.71},
                },
            ],
        }
    )
